export const privilegeConstants = {
  GET_PRIVILEGE_REQUEST: "GET_PRIVILEGE_REQUEST",
  GET_PRIVILEGE_SUCCESS: "GET_PRIVILEGE_SUCCESS",
  GET_PRIVILEGE_FAILURE: "GET_PRIVILEGE_FAILURE",
  GET_PRIVILEGE_ADMIN_REQUEST: "GET_PRIVILEGE_ADMIN_REQUEST",
  GET_PRIVILEGE_ADMIN_SUCCESS: "GET_PRIVILEGE_ADMIN_SUCCESS",
  GET_PRIVILEGE_ADMIN_FAILURE: "GET_PRIVILEGE_ADMIN_FAILURE",

  GET_USERS_BY_PRIV_REQUEST: "GET_USERS_BY_PRIV_REQUEST",
  GET_USERS_BY_PRIV_SUCCESS: "GET_USERS_BY_PRIV_SUCCESS",
  GET_USERS_BY_PRIV_FAILURE: "GET_USERS_BY_PRIV_FAILURE",
};
export const userConstants = {
  GET_ALL_USER_REQUEST: "GET_ALL_USER_REQUEST",
  GET_ALL_USER_FAILURE: "GET_ALL_USER_FAILURE",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",

  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",

  ALTER_USER_REQUEST: "ALTER_USER_REQUEST",
  ALTER_USER_SUCCESS: "ALTER_USER_SUCCESS",
  ALTER_USER_FAILURE: "ALTER_USER_FAILURE",

  DROP_USER_REQUEST: "DROP_USER_REQUEST",
  DROP_USER_SUCCESS: "DROP_USER_SUCCESS",
  DROP_USER_FAILURE: "DROP_USER_FAILURE",

  GET_CURRENT_USER_REQUEST: "GET_CURRENT_USER_REQUEST",
  GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_FAILURE: "GET_CURRENT_USER_FAILURE",
};

export const profileConstants = {
  GET_ALL_PROFILE_REQUEST: "GET_ALL_PROFILE_REQUEST",
  GET_ALL_PROFILE_FAILURE: "GET_ALL_PROFILE_FAILURE",
  GET_ALL_PROFILE_SUCCESS: "GET_ALL_PROFILE_SUCCESS",

  CREATE_PROFILE_REQUEST: "CREATE_PROFILE_REQUEST",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",

  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",

  ALTER_PROFILE_REQUEST: "ALTER_PROFILE_REQUEST",
  ALTER_PROFILE_SUCCESS: "ALTER_PROFILE_SUCCESS",
  ALTER_PROFILE_FAILURE: "ALTER_PROFILE_FAILURE",

  DROP_PROFILE_REQUEST: "DROP_PROFILE_REQUEST",
  DROP_PROFILE_SUCCESS: "DROP_PROFILE_SUCCESS",
  DROP_PROFILE_FAILURE: "DROP_PROFILE_FAILURE",

  GET_USERS_BY_PROFILE_REQUEST: "GET_USERS_BY_PROFILE_REQUEST",
  GET_USERS_BY_PROFILE_SUCCESS: "GET_USERS_BY_PROFILE_SUCCESS",
  GET_USERS_BY_PROFILE_FAILURE: "GET_USERS_BY_PROFILE_FAILURE",
};

export const roleConstants = {
  GET_ALL_ROLE_REQUEST: "GET_ALL_ROLE_REQUEST",
  GET_ALL_ROLE_FAILURE: "GET_ALL_ROLE_FAILURE",
  GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",

  CREATE_ROLE_REQUEST: "CREATE_ROLE_REQUEST",
  CREATE_ROLE_FAILURE: "CREATE_ROLE_FAILURE",
  CREATE_ROLE_SUCCESS: "CREATE_ROLE_SUCCESS",

  GET_ROLE_REQUEST: "GET_ROLE_REQUEST",
  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_ROLE_FAILURE: "GET_ROLE_FAILURE",

  ALTER_ROLE_REQUEST: "ALTER_ROLE_REQUEST",
  ALTER_ROLE_SUCCESS: "ALTER_ROLE_SUCCESS",
  ALTER_ROLE_FAILURE: "ALTER_ROLE_FAILURE",

  DROP_ROLE_REQUEST: "DROP_ROLE_REQUEST",
  DROP_ROLE_SUCCESS: "DROP_ROLE_SUCCESS",
  DROP_ROLE_FAILURE: "DROP_ROLE_FAILURE",

  GRANT_ROLE_PRIV_REQUEST: "GRANT_ROLE_PRIV_REQUEST",
  GRANT_ROLE_PRIV_SUCCESS: "GRANT_ROLE_PRIV_SUCCESS",
  GRANT_ROLE_PRIV_FAILURE: "GRANT_ROLE_PRIV_FAILURE",

  REVOKE_ROLE_PRIV_REQUEST: "REVOKE_ROLE_PRIV_REQUEST",
  REVOKE_ROLE_PRIV_SUCCESS: "REVOKE_ROLE_PRIV_SUCCESS",
  REVOKE_ROLE_PRIV_FAILURE: "REVOKE_ROLE_PRIV_FAILURE",

  GET_ALL_PRIV_BY_ROLE_REQUEST: "GET_ALL_PRIV_BY_ROLE_REQUEST",
  GET_ALL_PRIV_BY_ROLE_SUCCESS: "GET_ALL_PRIV_BY_ROLE_SUCCESS",
  GET_ALL_PRIV_BY_ROLE_FAILURE: "GET_ALL_PRIV_BY_ROLE_FAILURE",

  GET_ALL_USER_BY_ROLE_REQUEST: "GET_ALL_USER_BY_ROLE_REQUEST",
  GET_ALL_USER_BY_ROLE_SUCCESS: "GET_ALL_USER_BY_ROLE_SUCCESS",
  GET_ALL_USER_BY_ROLE_FAILURE: "GET_ALL_USER_BY_ROLE_FAILURE",

  GET_ALL_ROLE_BY_USER_REQUEST: "GET_ALL_ROLE_BY_USER_REQUEST",
  GET_ALL_ROLE_BY_USER_SUCCESS: "GET_ALL_ROLE_BY_USER_SUCCESS",
  GET_ALL_ROLE_BY_USER_FAILURE: "GET_ALL_ROLE_BY_USER_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  GET_PRIVILEGE_REQUEST: "GET_PRIVILEGE_REQUEST",
  GET_PRIVILEGE_SUCCESS: "GET_PRIVILEGE_SUCCESS",
  GET_PRIVILEGE_FAILURE: "GET_PRIVILEGE_FAILURE",
};

export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
};
export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_FAILURE: "GET_PRODUCT_DETAIL_FAILURE",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_REQUEST: "ENABLE_PRODUCT_REQUEST",
  ENABLE_PRODUCT_SUCCESS: "ENABLE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_FAILURE: "ENABLE_PRODUCT_FAILURE",
};
export const initialDataConstants = {
  GET_INITIALDATA_REQUEST: "GET_INITIALDATA_REQUEST",
  GET_INITIALDATA_FAILURE: "GET_INITIALDATA_FAILURE",
  GET_INITIALDATA_SUCCESS: "GET_INITIALDATA_SUCCESS",
};
export const pageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
};

export const orderConstants = {
  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",

  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  UPDATE_ORDER_FAILURE: "UPDATE_ORDER_FAILURE",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",

  GET_ORDER_DETAIL_REQUEST: "GET_ORDER_DETAIL_REQUEST",
  GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
  GET_ORDER_DETAIL_FAILURE: "GET_ORDER_DETAIL_FAILURE",
};
